apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-react-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-react
  template:
    metadata:
      labels:
        app: hello-react
    spec:
      containers:
      - name: hello-react
        image: haridstu/hello-react:latest
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_API_URL
          value: "http://hello-api-service:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-react-service
spec:
  type: LoadBalancer
  selector:
    app: hello-react
  ports:
  - port: 80
    targetPort: 80